services:
  lint:
    container_name: dqo-lint
    build:
      context: .
      dockerfile: Dockerfile
      target: lint
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1

  test:
    container_name: dqo-test
    build:
      context: .
      dockerfile: Dockerfile
      target: test
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
