sonar.projectKey=chrysa_django-query-optimizer
sonar.organization=chrysa
sonar.projectName=django-query-optimizer

sonar.sources=src
sonar.tests=tests

sonar.python.version=3.14
sonar.python.coverage.reportPaths=coverage.xml

sonar.sourceEncoding=UTF-8

sonar.exclusions=\
  **/__pycache__/**,\
  **/*.pyc,\
  src/django_query_optimizer/testing/**

sonar.coverage.exclusions=\
  src/django_query_optimizer/testing/**,\
  tests/**
